package com.lyh.aiagent.tools;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PdfToolTest {

    private static final PdfTool pdfTool = new PdfTool();
    private static final Path baseDir = Path.of("data", "tool-files", "pdfs");
    private static final String testFilename = "test_report.pdf";
    private static final String testContent = "Hello World! This is a test PDF generated by iText 7.";

    @AfterAll
    static void cleanup() throws Exception {
        if (!Files.exists(baseDir)) {
            return;
        }
        try (Stream<Path> pathStream = Files.walk(baseDir)) {
            pathStream
                    .sorted(Comparator.reverseOrder())
                    .filter(path -> !path.equals(baseDir))
                    .forEach(path -> {
                        try {
                            Files.deleteIfExists(path);
                        } catch (Exception e) {
                            throw new RuntimeException(e);
                        }
                    });
        }
    }

    @Test
    @Order(1)
    void shouldGeneratePdf() {
        String result = pdfTool.generatePdf(testFilename, testContent);

        // 验证返回结果中包含成功关键字
        assertTrue(result.contains("PDF文件生成成功"));
        assertTrue(result.contains(testFilename));

        // 验证文件确实被生成到了指定目录
        Path targetPath = baseDir.resolve(testFilename);
        assertTrue(Files.exists(targetPath));
        assertTrue(targetPath.toFile().length() > 0);
    }
}
